### ISSUE TITLE
integrate Arctic DEM into prototype

### ISSUE THREAD

**Issue by abrin** [digital-antiquity/DataARC#12]
http://us3.campaign-archive2.com/?u=9b55d57c1b3978d7f1133ad68&id=6e026abc85&e=

Wonder if there's  a Leaflet plugin or other integration tool

**Comment by cstrawhacker** [comment]
PGC said they would release the maps via a web service, so I'm hoping that's the case. I can email Paul Morin and see if that's still the case, if you want.

**Comment by abrin** [comment]
I think this was done
