### ISSUE TITLE
concept map doesn't work in Internet explorer

### ISSUE THREAD

**Issue by abrin** [digital-antiquity/DataARC#21]
could you please look at the concept map in IE at some point in the next month? It doesn't seem to work here in Scotland. 

thanks

**Comment by bigjohn-cast** [comment]
Works in IE now, though there is an issue with displaying the initial layout. I'm not sure what I can do about it.

**Comment by abrin** [comment]
Probably not worth spending too much time here until we start to figure out a new UI for the client. We’re not scrapping the concept-map, but we do need to redo the overall interface.
