### ISSUE TITLE
Map Extent Only on Iceland

### ISSUE THREAD

**Issue by cstrawhacker** [digital-antiquity/DataARC#46]
Extent on the map filter is only focused on Iceland, so users will not see that we have data outside of Iceland. Perhaps we can make the map extent top current data extent? Or if SEAD data make that complicated, have it centered on southern Greenland, Iceland and Orkney?

**Comment by abrin** [comment]
Sure, we can extend this pretty easily, we just cropped it for performance reasons.

**Comment by abrin** [comment]
zoomed out to better cover a broader extent

**Comment by abrin** [comment]
I'm going to close this, if you want to better adjust the coords, just re-open or let me know.

**Comment by cstrawhacker** [comment]
Sounds good! Thanks. :)

Colleen


--
__________________________________________________

Colleen Strawhacker, Ph.D.
Research Scientist I
National Snow and Ice Data Center
Cooperative Institute for Research in Environmental Science (CIRES)
University of Colorado, Boulder
449 UCB
Boulder, CO 80309
303.492.9653 (office)
215.806.2205 (cell)
Follow me on Twitter @ArchaeoHacker
http://www.colleenstrawhacker.com
