### ISSUE TITLE
standardize feature properties in geojson include files

### ISSUE THREAD

**Issue by tsxtn** [digital-antiquity/DataARC#57]
We need `properties.id` and `properties.name` for all features in the geojson files so when we display for the filter we know what to expect. Right now we are using `properties.name` (Greenland) and `properties.SVIETARFEL` (Iceland).

**Comment by abrin** [comment]
done

**Comment by abrin** [comment]
I deployed with the changes and now see the following:

```
[Warning] jQuery.Deferred exception: undefined is not an object (evaluating 'Geography.pLayers[layerid]') (2) (jquery.min.js, line 2)
update — filter.js:87
refresh — filter.js:48
after — global.js:26
(anonymous function) — search.js:91
l — jquery.min.js:2:29381
(anonymous function) — jquery.min.js:2:29679
undefined
[Log] Matched Failed – TypeError: undefined is not an object (evaluating 'Geography.pLayers[layerid]') (search.js, line 93)
TypeError: undefined is not an object (evaluating 'Geography.pLayers[layerid]')
```

**Comment by tsxtn** [comment]
This is already fixed in the webapp branch. Geography.pLayers is the old code. That filter function should call `Geography.getGeojsonFeature` instead.

**Comment by abrin** [comment]
There must have been a caching issue, working now
